name: Test Build

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - main

jobs:
  check_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/build
        with:
          # TODO: make arch_name optional (dont upload artifact)
          # TODO: make this a matrix for architectures to test build?
          arch_name: x86_64
