name: Build Project

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - arch_name: x86_64
            cc: gcc
            cflags:
          - arch_name: x64
            cc: gcc
            cflags: -m32

    steps:
    - uses: actions/checkout@v4
    - uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: libpam0g-dev
        version: 1.0

    - name: Build Code
      run: |
        make CC=${{ matrix.cc }} CFLAGS="-O3 ${{ cflags }}"
        mv lidm lidm-${{ matrix.arch_name }}

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: build-${{ matrix.arch_name }}
        path: lidm-${{ matrix.arch_name }}

  merge-builds:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Merge Artifacts
        uses: actions/upload-artifact/merge@v4
        with:
          name: all-builds
          pattern: build-*
          delete-merged: true
          retention-days: 1
