name: Check and Build Release

on:
  workflow_dispatch:
    inputs:
      version:
        required: true
        default: ''
        type: string

jobs:
  build:
    name: Check and Build
    uses: ./.github/workflows/check-and-build.yml
    permissions: write-all
    with:
      set-statuses: false

  release:
    name: Make Release v${{ inputs.version }}
    runs-on: ubuntu-24.04
    container: archlinux:latest
    permissions: write-all
    needs: build
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: builds
          pattern: build-*
          merge-multiple: true

      - uses: ncipollo/release-action@v1
        with:
          tag: v${{ inputs.version }}
          commit: ${{ github.sha }}
          artifacts: builds/lidm-*
          artifactsErrorsFailBuild: true
          body: Release notes not generated yet.

      - uses: actions/checkout@v4
        with:
          ref: 'v${{ inputs.version }}'

      - uses: uraimo/run-on-arch-action@v2
        with:
          arch: riscv64
          distro: ubuntu22.04
          githubToken: ${{ github.token }}
          install: |
            apt-get update && \
            apt-get install -y make gcc libpam0g-dev
          run: |
            cd "assets/pkg/aur"
            ./update-pkgs.sh ${{ inputs.version }}
            ./test-makepkg.sh # This will also update -git pkgver

      - uses: peter-evans/create-pull-request@v7
        with:
          commit-message: Update AUR pkgs to v${{ inputs.version }}
