name: Check and Build Release

on:
  workflow_dispatch:
    inputs:
      version:
        required: true
        default: ''
        type: string

jobs:
  build:
    name: Check and Build
    uses: ./.github/workflows/check-and-build.yml
    permissions: write-all
    with:
      set-statuses: false

  release:
    name: Make Release v${{ inputs.version }}
    runs-on: ubuntu-24.04
    container: archlinux:latest
    permissions: write-all
    needs: build
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: builds
          pattern: build-*
          merge-multiple: true

      - uses: ncipollo/release-action@v1
        with:
          tag: v${{ inputs.version }}
          commit: ${{ github.sha }}
          artifacts: builds/lidm-*
          artifactErrorsFailBuild: true
          body: Release notes not generated yet.

      - uses: actions/checkout@v4
        with:
          ref: 'v${{ inputs.version }}'

      - run: pacman -Sy --noconfirm pacman-contrib

      - run: |
          cd "assets/pkg/aur"
          chown nobody:nobody . -R
          su - -s /bin/bash nobody -c "$PWD/update-pkgs.sh ${{ inputs.version }}"
          su - -s /bin/bash nobody -c "$PWD/test-makepkg.sh" # This will also update -git pkgver

      - uses: peter-evans/create-pull-request@v7
        with:
          commit-message: Update AUR pkgs to v${{ inputs.version }}
