name: Check and Build Release

on:
  workflow_dispatch:
    inputs:
      version:
        required: true
        default: ''
        type: string

jobs:
  build:
    name: Check and Build
    uses: ./.github/workflows/check-and-build.yml
    permissions: write-all
    with:
      set-statuses: false

  release:
    name: Make Release v${{ inputs.version }}
    runs-on: ubuntu-24.04
    permissions: write-all
    needs: build
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: builds
          pattern: build-*
          merge-multiple: true

      - uses: ncipollo/release-action@v1
        with:
          tag: v${{ inputs.version }}
          commit: ${{ github.sha }}
          artifacts: builds/lidm-*
          artifactErrorsFailBuild: true
          body: Release notes not generated yet.

  aur-update:
    name: Update AUR pkgs
    runs-on: ubuntu-24.04
    container: archlinux:latest
    permissions: write-all
    needs: release
    steps:
      - run: pacman -Sy --noconfirm git github-cli base-devel pacman-contrib

      - uses: actions/checkout@v4

      - run: |
          cd "assets/pkg/aur"
          chown nobody:nobody . -R
          su - -s /bin/bash nobody -c "$PWD/update-pkgs.sh ${{ inputs.version }}"
          su - -s /bin/bash nobody -c "$PWD/test-makepkg.sh" # This will also update -git pkgver
          echo "# test"  >> update-pkgs.sh
          chown $UID:$(id -g) . -R

      - run: |
          BRANCH=actions/update-aur-${{ inputs.version }}
          git config --global --add safe.directory $GITHUB_WORKSPACE
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git checkout -b $BRANCH
          git commit -am "Update AUR pkgs to v${{ inputs.version }}"
          git push -u origin $BRANCH
          gh pr create --head $BRANCH \
            --title "[AUR update]: Bump to ${{ inputs.version }}" \
            --body "*This PR was created automatically*"
        env:
          GH_TOKEN: ${{ github.token }}
