name: Build for Release

on:
  release:
    types: [created]

jobs:
  release:
    permissions: write
    runs-on: ubuntu-latest

    steps:
      - name: Build Project
        uses: ./.github/workflows/build.yml

      - uses: actions/download-artifact@v4
        with:
          name: all-builds
          path: builds

      - name: Upload Builds to Release
        run: |
          cd builds
          for file in ./*; do
            echo "Uploading $file..."
            gh release upload ${{ github.event.release.tag_name }} "$file" --clobber
          done
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
